version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "mail:1:1"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app-network

  mongo:
    image: "mongo:5.0.14"
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - kafka
    networks:
      - app-network

networks:
  app-network:
      driver: bridge
